"""Markdown report generator.

Produces a complete audit report in Markdown — useful for committing to a
client's repo, pasting into a ticket, or feeding to a PDF converter.
"""
from __future__ import annotations

from .models import AuditReport, Severity

SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
SEVERITY_BADGE = {
    "Critical": "🔴",
    "High": "🟠",
    "Medium": "🟡",
    "Low": "🔵",
    "Informational": "⚪",
}


def render_markdown(report: AuditReport) -> str:
    out: list[str] = []
    out.append(f"# Microsoft 365 Security Posture Assessment\n")
    out.append(f"**Tenant:** {report.tenant_name}\n")
    out.append(f"**Tenant ID:** `{report.tenant_id}`\n")
    out.append(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}\n")
    out.append(f"**Auditor:** {report.auditor}\n\n")

    out.append("---\n")
    out.append("## Executive Summary\n")
    out.append(f"**Posture Grade: {report.posture_grade}** &nbsp; ")
    out.append(f"**Risk Score: {report.risk_score}/100**\n\n")

    counts = report.summary_counts
    out.append("| Severity | Findings |\n|---|---|\n")
    for sev in SEVERITY_ORDER:
        out.append(f"| {SEVERITY_BADGE[sev.value]} {sev.value} | {counts[sev.value]} |\n")
    out.append("\n")

    summary = []
    if counts["Critical"]:
        summary.append(f"**{counts['Critical']} Critical** finding(s) require immediate remediation.")
    if counts["High"]:
        summary.append(f"**{counts['High']} High** severity finding(s) should be addressed within 30 days.")
    if not counts["Critical"] and not counts["High"]:
        summary.append("No Critical or High severity findings.")
    out.append(" ".join(summary) + "\n\n")

    out.append("## Findings by Severity\n")
    for sev in SEVERITY_ORDER:
        items = [f for f in report.all_findings if f.severity == sev]
        if not items:
            continue
        out.append(f"### {SEVERITY_BADGE[sev.value]} {sev.value} ({len(items)})\n")
        for f in items:
            out.append(f"#### {f.check_id} — {f.title}\n")
            out.append(f"**Description:** {f.description}\n\n")
            out.append(f"**Impact:** {f.impact}\n\n")
            out.append(f"**Recommendation:** {f.recommendation}\n\n")
            if f.affected_objects:
                shown = f.affected_objects[:10]
                out.append(f"**Affected objects ({len(f.affected_objects)}):** ")
                out.append(", ".join(f"`{o}`" for o in shown))
                if len(f.affected_objects) > 10:
                    out.append(f", _… {len(f.affected_objects) - 10} more_")
                out.append("\n\n")
            if f.references:
                out.append("**References:**\n")
                for r in f.references:
                    out.append(f"- {r}\n")
                out.append("\n")

    out.append("## Checks Executed\n")
    out.append("| Check ID | Name | Category | Status | Findings |\n|---|---|---|---|---|\n")
    for r in report.results:
        out.append(f"| {r.check_id} | {r.name} | {r.category} | {r.status.value} | {len(r.findings)} |\n")

    errored = [r for r in report.results if r.status.value == "Error"]
    if errored:
        out.append("\n### Checks that errored\n")
        for r in errored:
            out.append(f"- **{r.check_id}** — {r.error_message}\n")

    out.append("\n---\n")
    out.append("_Report generated by m365-posture-auditor. This is an automated assessment; "
               "manual review by a qualified practitioner is recommended for any finding "
               "before remediation._\n")
    return "".join(out)
