"""HTML report generator."""
from __future__ import annotations
from .models import AuditReport, Severity

SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
SEVERITY_COLOR = {"Critical":"#dc2626","High":"#ea580c","Medium":"#ca8a04","Low":"#2563eb","Informational":"#6b7280"}
GRADE_COLOR = {"A":"#16a34a","A-":"#22c55e","B":"#65a30d","C":"#ca8a04","D":"#ea580c","F":"#dc2626"}
EMOJI = {"Critical":"🔴","High":"🟠","Medium":"🟡","Low":"🔵","Informational":"⚪"}
CSS = "* { box-sizing: border-box; margin: 0; padding: 0; } body { font-family: -apple-system, sans-serif; background: #f8fafc; color: #1e293b; font-size: 15px; } .container { max-width: 960px; margin: 0 auto; padding: 32px 24px; } header { background: #0f172a; color: white; padding: 32px 24px; margin-bottom: 32px; border-radius: 8px; } header h1 { font-size: 22px; font-weight: 700; } .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 32px; } .summary-card { background: white; border-radius: 8px; padding: 20px; border: 1px solid #e2e8f0; text-align: center; } .label { font-size: 12px; text-transform: uppercase; color: #64748b; margin-bottom: 8px; } .value { font-size: 32px; font-weight: 800; } .section { background: white; border-radius: 8px; border: 1px solid #e2e8f0; margin-bottom: 24px; } .section-header { padding: 16px 20px; border-bottom: 1px solid #e2e8f0; font-size: 16px; font-weight: 600; } .finding { padding: 20px; border-bottom: 1px solid #f1f5f9; } .badge { display: inline-block; font-size: 11px; font-weight: 700; padding: 2px 8px; border-radius: 4px; color: white; margin-right: 8px; } .checks-table { width: 100%; border-collapse: collapse; font-size: 13px; } .checks-table th { background: #f8fafc; padding: 10px 16px; text-align: left; border-bottom: 2px solid #e2e8f0; } .checks-table td { padding: 10px 16px; border-bottom: 1px solid #f1f5f9; } footer { text-align: center; font-size: 12px; color: #94a3b8; margin-top: 32px; }"

def render_html(report: AuditReport) -> str:
    grade = report.posture_grade
    grade_color = GRADE_COLOR.get(grade, "#6b7280")
    counts = report.summary_counts
    generated = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    p = []
    p.append(f'<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>M365 Security Posture</title><style>{CSS}</style></head><body><div class="container">')
    p.append(f'<header><h1>Microsoft 365 Security Posture Assessment</h1><div style="font-size:13px;color:#94a3b8;margin-top:8px">{report.tenant_name} &nbsp;·&nbsp; {generated}</div></header>')
    p.append('<div class="summary-grid">')
    p.append(f'<div class="summary-card"><div class="label">Grade</div><div class="value" style="color:{grade_color}">{grade}</div></div>')
    p.append(f'<div class="summary-card"><div class="label">Risk Score</div><div class="value">{report.risk_score}/100</div></div>')
    for sev in SEVERITY_ORDER:
        count = counts[sev.value]
        color = SEVERITY_COLOR.get(sev.value,"#6b7280") if count > 0 else "#94a3b8"
        p.append(f'<div class="summary-card"><div class="label">{EMOJI[sev.value]} {sev.value}</div><div class="value" style="color:{color}">{count}</div></div>')
    p.append('</div><div class="section"><div class="section-header">Findings</div>')
    all_findings = report.all_findings
    if not all_findings:
        p.append('<div class="finding">No findings — all checks passed.</div>')
    else:
        for f in all_findings:
            color = SEVERITY_COLOR.get(f.severity.value,"#6b7280")
            p.append(f'<div class="finding"><span class="badge" style="background:{color}">{f.severity.value}</span><strong>{f.check_id} — {f.title}</strong><p style="margin-top:8px;font-size:14px">{f.recommendation}</p></div>')
    p.append('</div><div class="section"><div class="section-header">Checks Executed</div>')
    p.append('<table class="checks-table"><thead><tr><th>Check ID</th><th>Name</th><th>Status</th></tr></thead><tbody>')
    for r in report.results:
        p.append(f'<tr><td><code>{r.check_id}</code></td><td>{r.name}</td><td>{r.status.value}</td></tr>')
    p.append('</tbody></table></div><footer>Report generated by m365-posture-auditor.</footer></div></body></html>')
    return "".join(p)
